// Generated by Addresses AddressesAssetEditor v1.0.2
// from asset: Assets/TinyGoose/Addresses/Sample/Addresses.asset

using UnityEngine;
using TinyGoose.Addresses;

namespace MyGame
{
	public static class Addresses
	{
		// -----------------------------------------------------------------------------------------------------------------------------
		// 		Addressable Group: Default Local Group
		// -----------------------------------------------------------------------------------------------------------------------------

		// Material: Assets/TinyGoose/Addresses/Sample/Materials/M_Sample.mat
		public static Address<Material> M_Sample => new("M_Sample");

		// GameObject: Assets/TinyGoose/Addresses/Sample/Prefabs/P_Light.prefab
		public static Address<GameObject> P_Light => new("P_Light");

		// -----------------------------------------------------------------------------------------------------------------------------
		// 		Addressable Group: Other Cool Group
		// -----------------------------------------------------------------------------------------------------------------------------
		public static class OtherCoolGroup
		{
			// Material: Assets/TinyGoose/Addresses/Sample/Materials/M_Sample_InOtherGroup.mat
			public static Address<Material> M_Sample_InOtherGroup => new("M_Sample_InOtherGroup");
		}

		// -----------------------------------------------------------------------------------------------------------------------------
		// 		Addressable Group: Folders
		// -----------------------------------------------------------------------------------------------------------------------------
		public static class Folders
		{
			// -----------------------------------------------------------------------------------------------------------------------------
			// 		Folder: Assets/TinyGoose/Addresses/Sample/MiscAddressables
			// -----------------------------------------------------------------------------------------------------------------------------
			// Material: Assets/TinyGoose/Addresses/Sample/MiscAddressables/M_Sample_InFolder.mat
			public static Address<Material> M_Sample_InFolder => new("MiscAddressables/M_Sample_InFolder.mat");

			// GameObject: Assets/TinyGoose/Addresses/Sample/MiscAddressables/P_LightInFolder.prefab
			public static Address<GameObject> P_LightInFolder => new("MiscAddressables/P_LightInFolder.prefab");
		}
	}
}
